world:
  bounds:
    min:
    - -20.0
    - -20.0
    - -20.0
    max:
    - 20.0
    - 20.0
    - 20.0
obstacles:
  count: 5
  default_size:
  - 2.0
  - 2.0
  - 2.0
  positions:
  - center:
    - 5.04
    - 9.65
    - 10.24
    size:
    - 1.67
    - 1.67
    - 1.67
  - center:
    - -4.47
    - 6.0
    - 0.69
    size:
    - 1.43
    - 1.43
    - 1.43
  - center:
    - -13.75
    - 11.14
    - 6.23
    size:
    - 1.67
    - 1.67
    - 1.67
  - center:
    - 12.46
    - 6.35
    - 11.84
    size:
    - 1.58
    - 1.58
    - 1.58
  - center:
    - -16.32
    - -8.18
    - -11.71
    size:
    - 2.4
    - 2.4
    - 2.4
agents:
  default_radius: 0.5
  default_speed: 2.0
  agent_list:
  - id: 0
    start:
    - -9.26
    - 17.2
    - -5.23
    goal:
    - 12.25
    - -4.59
    - -8.31
    color:
    - 0.73
    - 0.86
    - 0.61
    radius: 0.5
    speed: 2.0
  - id: 1
    start:
    - 5.15
    - -13.7
    - 3.99
    goal:
    - 16.35
    - 16.97
    - 15.08
    color:
    - 0.13
    - 0.79
    - 0.66
    radius: 0.5
    speed: 2.0
  - id: 2
    start:
    - -7.9
    - 10.11
    - -16.84
    goal:
    - -0.24
    - -16.93
    - -16.39
    color:
    - 0.35
    - 0.55
    - 0.24
    radius: 0.5
    speed: 2.0
  - id: 3
    start:
    - 13.96
    - 1.27
    - 0.59
    goal:
    - 6.31
    - 14.05
    - 1.78
    color:
    - 0.65
    - 0.19
    - 0.38
    radius: 0.5
    speed: 2.0
  - id: 4
    start:
    - -9.33
    - -6.5
    - -17.87
    goal:
    - -0.44
    - 9.11
    - 15.28
    color:
    - 0.9
    - 0.36
    - 0.92
    radius: 0.5
    speed: 2.0
